apiVersion: v1
kind: Service
metadata:
  name: sagemaker-fastapi-svc-kh
spec:
  selector:
    app: sagemaker-fastapi-kh
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
